/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.EntrenadorData;
import entidades.Entrenador;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CCMEW
 */
public class gestionEntrenador extends javax.swing.JInternalFrame {

    private EntrenadorData eData = new EntrenadorData();
    private Entrenador entrenador = null;

    /**
     * Creates new form gestionSocios
     */
    public gestionEntrenador() {
        initComponents();
        int x = JFInicio.escritorio.getWidth() - this.getWidth();
        int y = JFInicio.escritorio.getHeight() - this.getHeight();
        setLocation(x / 2, y / 2);
        jTextCodigo.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jTextDni = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextEspecialidad = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("GESTION ENTRENADORES - ABM");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entrenador.png"))); // NOI18N
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 340, 350));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconNuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 120, 70));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconEliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, -1, 70));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconGuardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, 70));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconSalir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, 120, 70));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("NOMBRE:");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 120, 40));

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("CÓDIGO:");
        jLabelCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabelCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 120, 40));

        jLabelDni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDni.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDni.setText("DNI:");
        jPanel1.add(jLabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 50, 40));

        jLabelApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("APELLIDO:");
        jPanel1.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 120, 40));

        jLabelEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("ESPECIALIDAD:");
        jPanel1.add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 140, 40));

        jTextCodigo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextCodigo.setForeground(new java.awt.Color(0, 51, 153));
        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 100, 30));

        jTextDni.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextDni.setForeground(new java.awt.Color(0, 51, 153));
        jTextDni.setToolTipText("solo números sin punto");
        jTextDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDniKeyTyped(evt);
            }
        });
        jPanel1.add(jTextDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 120, 30));

        jTextNombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextNombre.setForeground(new java.awt.Color(0, 51, 153));
        jTextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreFocusLost(evt);
            }
        });
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 260, 30));

        jTextApellido.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextApellido.setForeground(new java.awt.Color(0, 51, 153));
        jTextApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextApellidoFocusLost(evt);
            }
        });
        jTextApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 260, 30));

        jTextEspecialidad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextEspecialidad.setForeground(new java.awt.Color(0, 51, 153));
        jTextEspecialidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEspecialidadFocusLost(evt);
            }
        });
        jPanel1.add(jTextEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 220, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tituloEntrenadores.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -40, 560, 230));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoFormulario.jpeg"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos() {
        jTextCodigo.setText("");
        jTextDni.setText("");
        jTextApellido.setText("");
        jTextNombre.setText("");
        jTextEspecialidad.setText("");
//        jTextCodigo.setEnabled(true);
        entrenador = null;

    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    // limita que solo se ingresen 8 caracteres
    private void jTextDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDniKeyTyped

        if (jTextDni.getText().length() >= 8) {  //maximo de caracteres
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_jTextDniKeyTyped

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jLabelCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelCodigoKeyTyped
        char c = evt.getKeyChar(); // para ingresar solo numeros
        if (c < '0' || c > '9')
            evt.consume();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabelCodigoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            Integer dni = Integer.parseInt(jTextDni.getText());
            String nombre = jTextNombre.getText();
            String apellido = jTextApellido.getText();
            String especialidad = jTextEspecialidad.getText();

            if (dni == null || apellido.isEmpty() || nombre.isEmpty() || especialidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos deben completarse");
                return;
            }

            if (dni < 1) {
                JOptionPane.showMessageDialog(this, "El DNI ingresado es incorrecto");
                return;
            }

            if (entrenador == null) {
                entrenador = new Entrenador(dni, nombre, apellido, especialidad, true);
                eData.guardarEntrenador(entrenador);
            } else {
                entrenador.setDni(dni);
                entrenador.setNombre(nombre);
                entrenador.setApellido(apellido);
                entrenador.setEspecialidad(especialidad);
                eData.modificarEntrenador(entrenador);
            }
            jTextCodigo.setText(entrenador.getIdEntrenador()+"");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresá carácteres válidos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            Integer dni = Integer.valueOf(jTextDni.getText());
            entrenador = eData.buscarEntrenadorPorDni(dni);
            
            if (entrenador != null) {
                jTextCodigo.setText(entrenador.getIdEntrenador() + "");
                jTextApellido.setText(entrenador.getApellido());
                jTextNombre.setText(entrenador.getNombre());
                jTextEspecialidad.setText(entrenador.getEspecialidad());
            }else{
                limpiarCampos();
                jTextDni.setText(dni+"");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "DNI incorrecto");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (entrenador != null) {
             int response = JOptionPane.showConfirmDialog(this, 
            "Está seguro que quiere eliminar un entrenador", 
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            eData.eliminarEntrenador(entrenador.getIdEntrenador());
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Eliminación cancelada");
        }
    } else {
        JOptionPane.showMessageDialog(this, "No hay un entrenador seleccionado");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTextNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreFocusLost
        jTextNombre.setText(fomatoFrase(jTextNombre.getText()));
    }//GEN-LAST:event_jTextNombreFocusLost

    private void jTextApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextApellidoFocusLost
        jTextApellido.setText(fomatoFrase(jTextApellido.getText()));
    }//GEN-LAST:event_jTextApellidoFocusLost

    private void jTextEspecialidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEspecialidadFocusLost
        jTextEspecialidad.setText(fomatoFrase(jTextEspecialidad.getText()));
    }//GEN-LAST:event_jTextEspecialidadFocusLost

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        char c = evt.getKeyChar(); // para ingresar solo numeros
        if (!((c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c==' '))){//(c < 'a' || c > 'z')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidoKeyTyped
        char c = evt.getKeyChar(); // para ingresar solo numeros
        if (!((c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c==' '))){//(c < 'a' || c > 'z')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextApellidoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextEspecialidad;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
    
    //Utilidades
    private String fomatoFrase(String palabra) {
        if (!palabra.isEmpty()) {
            palabra = palabra.trim();
            palabra = palabra.toLowerCase();
            char[] array = palabra.toCharArray();
            array[0] = Character.toUpperCase(array[0]);
            for (int i = 1; i < array.length; i++) {
                if (array[i - 1] == ' ') {
                    array[i] = Character.toUpperCase(array[i]);
                }
            }
            palabra = "";
            for (char i : array) {
                palabra = palabra + i;
            }
        }
        return palabra;
    }
}
