/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.AsistenciaData;
import accesoADatos.ClaseData;
import accesoADatos.MembresiaData;
import accesoADatos.SocioData;
import entidades.Clase;
import entidades.Membresia;
import entidades.Socio;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CCMEW
 */
public class gestionMembresia extends javax.swing.JInternalFrame {
    
    private ClaseData cData = null;
    private MembresiaData mData = null;
    private SocioData sData = null;
    private AsistenciaData aData = null;
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form gestionSocios
     */
    public gestionMembresia() {
        initComponents();
        int x = JFInicio.escritorio.getWidth() - this.getWidth();
        int y = JFInicio.escritorio.getHeight() - this.getHeight();
        setLocation(x / 2, y / 2);
        
        cData = new ClaseData();
        mData = new MembresiaData();
        sData = new SocioData();
        aData = new AsistenciaData();
        ///jDateFAsistencia.setDate(Date.from(Instant.now()));

        llenarCombos();
        
        armarCabecera();
        actualizarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMembre = new javax.swing.JTable();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jComboBoxSocio = new javax.swing.JComboBox<>();
        jLabelNombre2 = new javax.swing.JLabel();
        jLabelNombre3 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jDateFFin = new com.toedter.calendar.JDateChooser();
        jDateFInicio = new com.toedter.calendar.JDateChooser();
        jLabelNombre4 = new javax.swing.JLabel();
        jTextCosto = new javax.swing.JTextField();
        jComboBoxPases = new javax.swing.JComboBox<>();
        jLabelFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("GESTION MEMBRESIAS - ALTA / RENOVACION");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconSalir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, 120, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/membresias.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -40, 560, 230));

        jTableMembre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DNI", "APELLIDO", "NOMBRE", "TELEFONO", "EMAIL"
            }
        ));
        jScrollPane1.setViewportView(jTableMembre);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 770, 270));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Ingrese Cantidad de pases:");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 220, 40));

        jLabelNombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setText("Seleccione Socio:");
        jPanel1.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 170, 40));

        jComboBoxSocio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxSocio.setForeground(new java.awt.Color(0, 0, 153));
        jComboBoxSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSocioActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 490, 30));

        jLabelNombre2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre2.setText("Fecha desde:");
        jPanel1.add(jLabelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 120, 40));

        jLabelNombre3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre3.setText("Fecha hasta:");
        jPanel1.add(jLabelNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 120, 40));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconNuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo/Renovar");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 160, 70));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconEliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 150, 70));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconGuardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, -1, 70));
        jPanel1.add(jDateFFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 532, 200, 30));

        jDateFInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateFInicioPropertyChange(evt);
            }
        });
        jPanel1.add(jDateFInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 200, 30));

        jLabelNombre4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre4.setText("Costo:");
        jPanel1.add(jLabelNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 70, 40));

        jTextCosto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextCosto.setForeground(new java.awt.Color(0, 51, 153));
        jTextCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCostoActionPerformed(evt);
            }
        });
        jTextCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCostoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 100, 30));

        jComboBoxPases.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxPases.setForeground(new java.awt.Color(0, 0, 153));
        jComboBoxPases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPasesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPases, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 180, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoFormulario.jpeg"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jComboBoxSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSocioActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_jComboBoxSocioActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jTextCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCostoActionPerformed

    private void jTextCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCostoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCostoKeyTyped

    private void jComboBoxPasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPasesActionPerformed

    private void jDateFInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateFInicioPropertyChange
        Date fInicio = jDateFInicio.getDate();
        if (fInicio != null) {
            jDateFFin.setDate(new Date(fInicio.getYear(),fInicio.getMonth(),fInicio.getDate()+30));
        }else{
            jDateFFin.setDate(null);
        }
    }//GEN-LAST:event_jDateFInicioPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Integer> jComboBoxPases;
    private javax.swing.JComboBox<Socio> jComboBoxSocio;
    private com.toedter.calendar.JDateChooser jDateFFin;
    private com.toedter.calendar.JDateChooser jDateFInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JLabel jLabelNombre4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMembre;
    private javax.swing.JTextField jTextCosto;
    // End of variables declaration//GEN-END:variables

    private void llenarCombos() {
        //llenarCombo
        List<Socio> lista = sData.listarSocios();
        for (Socio item : lista) {
            jComboBoxSocio.addItem(item);
        }
        jComboBoxSocio.setSelectedIndex(-1);
        
        jComboBoxPases.addItem(8);
        jComboBoxPases.addItem(12);
        jComboBoxPases.addItem(20);
        jComboBoxPases.setSelectedIndex(-1);
    }
    
    private void armarCabecera() {
        //armarcabecera
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Código");
        filaCabecera.add("DNI Socio");
        filaCabecera.add("Apellido");
        filaCabecera.add("Nombre");
        filaCabecera.add("Pases Disponibles");
        filaCabecera.add("Desde:");
        filaCabecera.add("Hasta:");
        filaCabecera.add("Costo");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        jTableMembre.setModel(modelo);
    }
    
    private void borrarFilasTabla() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    private void actualizarTabla() {
        borrarFilasTabla();
        //btnBorrarAsistencia.setEnabled(false);

        Socio socio = (Socio) jComboBoxSocio.getSelectedItem();
        List<Membresia> lista = null;
        if (socio != null) {
            lista = mData.membresiasPorSocio(socio.getIdSocio());
        } else {
            lista = mData.listadoMembresia();
        }
        
        for (Membresia aux : lista) {
            modelo.addRow(new Object[]{aux.getIdMembresia(), aux.getSocio().getDni(), aux.getSocio().getApellido(), aux.getSocio().getNombre(), aux.getCantPases(), aux.getfInicio(), aux.getfFin(), aux.getCosto()});
        }
    }
    
}
