/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import static java.awt.GridBagConstraints.BOTH;
import javax.swing.ImageIcon;

/**
 *
 * @author CCMEW
 */
public class JFInicio extends javax.swing.JFrame {

    /**
     * Creates new form JFInicio
     */
    public JFInicio() {
        initComponents();
//        this.setExtendedState(6);// el formulario ocupa toda la pantalla
        this.setLocationRelativeTo(null); // para centrar el Jframe
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconPesas.png")).getImage()); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSocios = new javax.swing.JMenu();
        jMenuAlta = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuEntrenadores = new javax.swing.JMenu();
        jMenuItemEntrenadores = new javax.swing.JMenuItem();
        jMenuItemListadoEntrenadores = new javax.swing.JMenuItem();
        jMenuClases = new javax.swing.JMenu();
        jMenuItemClasesListado = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemAsistencia = new javax.swing.JMenuItem();
        jMenuMembresias = new javax.swing.JMenu();
        jMenuAltaMembresia = new javax.swing.JMenuItem();
        jMenuItemListadoMembresias = new javax.swing.JMenuItem();
        JMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Gimnasios");
        setExtendedState(6);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoGym.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconUsuarios.png"))); // NOI18N
        jMenuSocios.setText("Socios");
        jMenuSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSociosMouseClicked(evt);
            }
        });
        jMenuSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSociosActionPerformed(evt);
            }
        });

        jMenuAlta.setText("ABM");
        jMenuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaActionPerformed(evt);
            }
        });
        jMenuSocios.add(jMenuAlta);

        jMenuItem1.setText("Listado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSocios.add(jMenuItem1);

        jMenuBar1.add(jMenuSocios);

        jMenuEntrenadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconEntrenador.png"))); // NOI18N
        jMenuEntrenadores.setText("Entrenadores");

        jMenuItemEntrenadores.setText("ABM");
        jMenuItemEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEntrenadoresActionPerformed(evt);
            }
        });
        jMenuEntrenadores.add(jMenuItemEntrenadores);

        jMenuItemListadoEntrenadores.setText("Listado");
        jMenuItemListadoEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoEntrenadoresActionPerformed(evt);
            }
        });
        jMenuEntrenadores.add(jMenuItemListadoEntrenadores);

        jMenuBar1.add(jMenuEntrenadores);

        jMenuClases.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconClases.png"))); // NOI18N
        jMenuClases.setText("Clases");

        jMenuItemClasesListado.setText("ABM");
        jMenuItemClasesListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClasesListadoActionPerformed(evt);
            }
        });
        jMenuClases.add(jMenuItemClasesListado);

        jMenuItem2.setText("Listado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuClases.add(jMenuItem2);

        jMenuItemAsistencia.setText("Asistencia");
        jMenuItemAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAsistenciaActionPerformed(evt);
            }
        });
        jMenuClases.add(jMenuItemAsistencia);

        jMenuBar1.add(jMenuClases);

        jMenuMembresias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconMembresia.png"))); // NOI18N
        jMenuMembresias.setText("Membresias");

        jMenuAltaMembresia.setText("ABM");
        jMenuAltaMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaMembresiaActionPerformed(evt);
            }
        });
        jMenuMembresias.add(jMenuAltaMembresia);

        jMenuItemListadoMembresias.setText("Listado ");
        jMenuItemListadoMembresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoMembresiasActionPerformed(evt);
            }
        });
        jMenuMembresias.add(jMenuItemListadoMembresias);

        jMenuBar1.add(jMenuMembresias);

        JMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconSalir.png"))); // NOI18N
        JMSalir.setText("Salir");
        JMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMSalirMouseClicked
        System.exit(0); 
    }//GEN-LAST:event_JMSalirMouseClicked

    private void jMenuSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSociosActionPerformed
     

    }//GEN-LAST:event_jMenuSociosActionPerformed

    private void jMenuSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSociosMouseClicked
       
    }//GEN-LAST:event_jMenuSociosMouseClicked

    private void jMenuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaActionPerformed
       gestionSocios socios = new gestionSocios();
        escritorio.add(socios);
        socios.show(); 
    }//GEN-LAST:event_jMenuAltaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         listadoSocios lista = new listadoSocios();
        escritorio.add(lista);
        lista.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEntrenadoresActionPerformed
        gestionEntrenador Entrenador = new gestionEntrenador();
        escritorio.add(Entrenador);
        Entrenador.show(); 
    }//GEN-LAST:event_jMenuItemEntrenadoresActionPerformed

    private void jMenuItemListadoEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoEntrenadoresActionPerformed
        listadoEntrenadores ListaEntrenadores = new listadoEntrenadores();
        escritorio.add(ListaEntrenadores);
        ListaEntrenadores.show(); 
    }//GEN-LAST:event_jMenuItemListadoEntrenadoresActionPerformed

    private void jMenuItemClasesListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClasesListadoActionPerformed
        gestionClases clases = new gestionClases();
        escritorio.add(clases);
        clases.show();
    }//GEN-LAST:event_jMenuItemClasesListadoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        listadoClases listclases = new listadoClases();
        escritorio.add(listclases);
        listclases.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuAltaMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaMembresiaActionPerformed
        gestionMembresia membre = new gestionMembresia();
        escritorio.add(membre);
        membre.show();
    }//GEN-LAST:event_jMenuAltaMembresiaActionPerformed

    private void jMenuItemListadoMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoMembresiasActionPerformed
        listadoMembresias listmembre = new listadoMembresias();
        escritorio.add(listmembre);
        listmembre.show();
    }//GEN-LAST:event_jMenuItemListadoMembresiasActionPerformed

    private void jMenuItemAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAsistenciaActionPerformed
        gestionAsistencia asiste = new gestionAsistencia();
        escritorio.add(asiste);
        asiste.show();
    }//GEN-LAST:event_jMenuItemAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMSalir;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuAlta;
    private javax.swing.JMenuItem jMenuAltaMembresia;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClases;
    private javax.swing.JMenu jMenuEntrenadores;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAsistencia;
    private javax.swing.JMenuItem jMenuItemClasesListado;
    private javax.swing.JMenuItem jMenuItemEntrenadores;
    private javax.swing.JMenuItem jMenuItemListadoEntrenadores;
    private javax.swing.JMenuItem jMenuItemListadoMembresias;
    private javax.swing.JMenu jMenuMembresias;
    private javax.swing.JMenu jMenuSocios;
    // End of variables declaration//GEN-END:variables
}
